/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blogmanager.view;

import blogmanager.database.DatabaseOperations;
import blogmanager.genel.Utilities;
import blogmanager.model.BlogDetail;
import blogmanager.model.User;

/**
 *
 * @author Rahman Yazgan
 */
public class ViewUserInformationsJDialog extends javax.swing.JDialog {

    private User selectedUser;
    private final DatabaseOperations databaseOperations;
    private String email;
    private String password;
    private String userName;
    private String accessPermission;

    /**
     * Creates new form ViewUserInformationsJDialog
     *
     * @param parent
     * @param modal
     * @param blogDetail
     */
    public ViewUserInformationsJDialog(java.awt.Frame parent, boolean modal, BlogDetail blogDetail) {
        super(parent, modal);
        initComponents();

        this.setLocationRelativeTo(parent);

        databaseOperations = new DatabaseOperations();
        selectedUser = blogDetail.getUser();

        getData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldUserName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxAccessPermission = new javax.swing.JComboBox();
        jButtonUpdateUserInformations = new javax.swing.JButton();

        setTitle("Kullanıcı Bilgisini Görüntüle");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Kullanıcı Bilgileri"));

        jTextFieldUserName.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel1.setText("Ad Soyad :");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setText("E-Posta :");

        jTextFieldEmail.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setText("Şifre :");

        jTextFieldPassword.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setText("Kullanıcı İzni :");

        jComboBoxAccessPermission.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jComboBoxAccessPermission.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Okur (Yorum yazabilir)", "Yazar (Blog sahibi olabilir)", "Yönetici (Tüm verilere erişebilir)" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxAccessPermission, 0, 1, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPassword)
                    .addComponent(jTextFieldEmail)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxAccessPermission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonUpdateUserInformations.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jButtonUpdateUserInformations.setText("Güncelle");
        jButtonUpdateUserInformations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateUserInformationsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonUpdateUserInformations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUpdateUserInformations)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelMain, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getData() {
        email = selectedUser.getEmail();
        userName = selectedUser.getUserName();
        password = selectedUser.getPassword();
        accessPermission = selectedUser.getAccessPermission();

        System.out.println(email + "\n" + userName + "\n" + password + "\n" + accessPermission);

        jTextFieldEmail.setText(email);
        jTextFieldUserName.setText(userName);
        jTextFieldPassword.setText(password);

        switch (accessPermission) {
            case "A":
                jComboBoxAccessPermission.setSelectedIndex(2);
                break;
            case "O":
                jComboBoxAccessPermission.setSelectedIndex(0);
                break;
            case "Y":
                jComboBoxAccessPermission.setSelectedIndex(1);
                break;
            default:
                jComboBoxAccessPermission.setSelectedIndex(0);
        }
    }

    // A: Yönetici(Admin), O: Okur(Reader), Y: Yazar(Author)
    private String getAccessPermission(int jComboBoxSelectedIndex) {
        switch (jComboBoxSelectedIndex) {
            case 2:
                accessPermission = "A";
                break;
            case 0:
                accessPermission = "O";
                break;
            case 1:
                accessPermission = "Y";
                break;
        }
        return accessPermission;
    }

    private boolean setUserInformation() {
        try {
            email = jTextFieldEmail.getText();
            userName = jTextFieldUserName.getText();
            password = jTextFieldPassword.getText();
            int selectedIndex = jComboBoxAccessPermission.getSelectedIndex();
            accessPermission = getAccessPermission(selectedIndex);

            selectedUser.setEmail(email);
            selectedUser.setPassword(password);
            selectedUser.setUserName(userName);
            selectedUser.setAccessPermission(accessPermission);
            selectedUser.setRecordDate(selectedUser.getRecordDate());
            return true;
        } catch (Exception ex) {
            Utilities.showMessageBox("Hata: " + ex.getMessage(), "ERROR");
            return false;
        }
    }

    private void jButtonUpdateUserInformationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateUserInformationsActionPerformed
        try {
            databaseOperations.getDBConnection();

            if (setUserInformation()) {
                databaseOperations.updateUserInfo(selectedUser);
                getData();
                Utilities.showMessageBox("Kullanıcı bilgileri güncellendi.", "INFORMATION");
            }

            databaseOperations.dbConnectionClose();
        } catch (Exception ex) {
            Utilities.showMessageBox("Hata: " + ex.getMessage(), "ERROR");
        }
    }//GEN-LAST:event_jButtonUpdateUserInformationsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUpdateUserInformations;
    private javax.swing.JComboBox jComboBoxAccessPermission;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
